import {
  getQuiz,
  requestQuiz,
  requestSuccess,
  requestError,
  saveAnswer,
  postResults,
  sendResults,
  sendResultsSuccess,
  sendResultsError,
} from './quiz';

import {
  userCreation,
  signUp,
  signUpSuccess,
  signUpError,
  updateProfile,
  updateProfileSuccess,
  updateProfileError,
  login,
  signIn,
  signInSuccess,
  signInError,
  signOut,
  signOutSuccess,
  signOutError,
  resetPassword,
  resetPasswordSuccess,
  resetPasswordError,
  requestUser,
  requestUserSuccess,
  requestUserError,
} from './auth';

const actions = {
  getQuiz,
  requestQuiz,
  requestSuccess,
  requestError,
  saveAnswer,
  postResults,
  sendResults,
  sendResultsSuccess,
  sendResultsError,
  userCreation,
  signUp,
  signUpSuccess,
  signUpError,
  updateProfile,
  updateProfileSuccess,
  updateProfileError,
  login,
  signIn,
  signInSuccess,
  signInError,
  signOut,
  signOutSuccess,
  signOutError,
  resetPassword,
  resetPasswordSuccess,
  resetPasswordError,
  requestUser,
  requestUserSuccess,
  requestUserError,
};
export default actions;
